AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Tasklist Backend

Parameters:
  Project: 
    Type: String
    Description: A shorthand for the project name to cluster resources
    Default: todolist
  Stage:
    Type: String
    Description: The stage for this backend
    Default: dev
  Env:
    Type: String
    Description: The environement for this project
    Default: main

Resources:
  FunctionLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location: src/layers/template.yml
      Parameters:
        BaseName: !Sub ${Project}-${Env}-${Stage}

  Database:
    Type: AWS::Serverless::Application
    Properties:
      Location: src/database/template.yml
      Parameters:
        BaseName: !Sub ${Project}-${Env}-${Stage}

  FunctionsIntegration:
    Type: AWS::Serverless::Application
    Properties:
      Location: src/functions/template.yml
      Parameters:
        BaseName: !Sub ${Project}-${Env}-${Stage}
        Layer: !GetAtt FunctionLayer.Outputs.Layer

  Apis:
    Type: AWS::Serverless::Application
    Properties:
      Location: src/apis/template.yml
      Parameters:
        BaseName: !Sub ${Project}-${Env}-${Stage}
        GetTasksFunctionArn: !GetAtt FunctionsIntegration.Outputs.GetTasksFunctionArn
        PostTaskFunctionArn: !GetAtt FunctionsIntegration.Outputs.PostTaskFunctionArn
